language: python
python:
- '2.7'
install:
- pip install .
script: python setup.py nosetests
deploy:
  provider: pypi
  user: wamonite
  password:
    secure: cVV0+nwn5SjwnUbBVvshce5dO6EneIbs4EcsztP1bCT0I8PC18IMPPhx8F0hEAdK0WvL0VZglruf/1zJlti0o/OzZEeleux8/uJ/4pbmQp7HOPSnwnKDlt4xzRgS9H+UavnnInBkBI2Qh08YnfEhiuek3wgdexcQlxhb/E0BDqU=
  on:
    tags: true
